on:
  workflow_dispatch:

jobs:
  job_id:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Verify 16KB page alignment
        uses: hotbrainstech/verify-16k-page-align-github-action@v1
        with:
          file: app/build/outputs/apk/release/app-release.apk
          include_x86: 'false'
